services:
  postgres:
    image: postgres
    container_name: postgres_container
    ports:
      - 5432:5432
    volumes:
      - "./data:/var/lib/postgresql"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pwd
  prometheus:
    image: prom/prometheus
    container_name: prometheus_container
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.development.yml:/etc/prometheus/prometheus.yml
  # jaeger:
  #   image: jaegertracing/all-in-one
  #   container_name: jaeger_container
  #   ports:
  #     - 5775:5775/udp
  #     - 6831:6831/udp
  #     - 6832:6832/udp
  #     - 5778:5778
  #     - 14268:14268
  #     - 14250:14250
  #     - 16686:16686
  #     - 14268:14268
  grafana:
    image: grafana/grafana
    container_name: grafana_container
    ports:
      - 3000:3000
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin