services:
  web-api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_started
  
  postgres:
    image: postgres
    ports:
      - "8001:5432"
    volumes:
      - "./data:/var/lib/postgresql"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pwd