services:
  web-api:
    build: .
    ports:
      - "8000:8000"
      - "8001:8001"
    depends_on:
      postgres:
        condition: service_started
      prometheus:
        condition: service_started
      grafana:
        condition: service_started
  postgres:
    image: postgres
    container_name: postgres_container
    ports:
      - 5432
    volumes:
      - "./data:/var/lib/postgresql"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pwd
  prometheus:
    image: prom/prometheus
    container_name: prometheus_container
    ports:
      - 9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana
    container_name: grafana_container
    ports:
      - 3000:3000
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
