services:
  postgres:
    image: postgres
    container_name: postgres_container
    ports:
      - 5432:5432
    volumes:
      - "./data:/var/lib/postgresql"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pwd
  prometheus:
    image: prom/prometheus
    container_name: prometheus_container
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.development.yml:/etc/prometheus/prometheus.yml
  jaeger:
    image: jaegertracing/all-in-one
    container_name: jaeger_container
    ports:
      - 4317:4317
      - 4318:4318
      - 16686:16686
  grafana:
    image: grafana/grafana
    container_name: grafana_container
    ports:
      - 3000:3000
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
  loki:
    image: grafana/loki
    container_name: loki_container
    ports:
      - 3100:3100
    command: -config.file=/etc/loki/local-config.yaml
