scrape_configs:
  - job_name: 'prometheus'
    scheme: https
    scrape_interval: 15s
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ['host.docker.internal:8001']